// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RMS.Api.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RMS.Api.Models.InventoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ReorderLevel")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("InventoryItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ItemName = "Prime Ribeye Beef Cut",
                            Quantity = 25.50m,
                            ReorderLevel = 10.00m,
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 2,
                            ItemName = "White Truffle Oil",
                            Quantity = 5.00m,
                            ReorderLevel = 2.00m,
                            Unit = "liters"
                        },
                        new
                        {
                            Id = 3,
                            ItemName = "Arborio Rice",
                            Quantity = 30.00m,
                            ReorderLevel = 10.00m,
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 4,
                            ItemName = "Brioche Buns",
                            Quantity = 120.00m,
                            ReorderLevel = 40.00m,
                            Unit = "pcs"
                        },
                        new
                        {
                            Id = 5,
                            ItemName = "Angus Ground Beef",
                            Quantity = 40.00m,
                            ReorderLevel = 15.00m,
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 6,
                            ItemName = "Belgian Dark Chocolate",
                            Quantity = 15.00m,
                            ReorderLevel = 5.00m,
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 7,
                            ItemName = "Vanilla Bean Gelato",
                            Quantity = 12.00m,
                            ReorderLevel = 4.00m,
                            Unit = "liters"
                        },
                        new
                        {
                            Id = 8,
                            ItemName = "Calamari Rings",
                            Quantity = 18.00m,
                            ReorderLevel = 8.00m,
                            Unit = "kg"
                        });
                });

            modelBuilder.Entity("RMS.Api.Models.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Main",
                            Description = "Prime ribeye grilled to perfection, basted with homemade garlic butter and served with roasted baby potatoes.",
                            ImageUrl = "",
                            IsAvailable = true,
                            Name = "Ribeye Steak with Garlic Butter",
                            Price = 32.00m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Main",
                            Description = "Creamy arborio rice loaded with wild forest mushrooms, fresh herbs, parmesan cheese, and drizzled with white truffle oil.",
                            ImageUrl = "",
                            IsAvailable = true,
                            Name = "Truffle Mushroom Risotto",
                            Price = 22.00m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Main",
                            Description = "Angus beef patty with smoked cheddar, caramelized onions, heirloom tomato, and truffle aioli on a toasted brioche bun.",
                            ImageUrl = "",
                            IsAvailable = true,
                            Name = "Signature Bistro Burger",
                            Price = 18.00m
                        },
                        new
                        {
                            Id = 4,
                            Category = "Dessert",
                            Description = "Decadent dark chocolate cake with a molten liquid center, dusted with powdered sugar and served with premium vanilla bean gelato.",
                            ImageUrl = "",
                            IsAvailable = true,
                            Name = "Lava Cake with Vanilla Gelato",
                            Price = 10.00m
                        },
                        new
                        {
                            Id = 5,
                            Category = "Appetizer",
                            Description = "Lightly battered, fried calamari rings served with house-made citrus-herb aioli and fresh lemon wedges.",
                            ImageUrl = "",
                            IsAvailable = true,
                            Name = "Crispy Calamari",
                            Price = 14.50m
                        },
                        new
                        {
                            Id = 6,
                            Category = "Drink",
                            Description = "Refreshing blend of fresh lemon juice, pressed ginger juice, elderflower syrup, and club soda over crushed ice.",
                            ImageUrl = "",
                            IsAvailable = true,
                            Name = "Bistro Mocktail / Lemon Ginger Fizz",
                            Price = 7.50m
                        });
                });

            modelBuilder.Entity("RMS.Api.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TableId")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("WaiterId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TableId");

                    b.HasIndex("WaiterId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("RMS.Api.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MenuItemId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("RMS.Api.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("CashierId")
                        .HasColumnType("integer");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CashierId");

                    b.HasIndex("OrderId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("RMS.Api.Models.Table", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TableNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tables");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 4,
                            Status = "occupied",
                            TableNumber = "T-01"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 2,
                            Status = "idle",
                            TableNumber = "T-02"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 6,
                            Status = "idle",
                            TableNumber = "T-03"
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 4,
                            Status = "occupied",
                            TableNumber = "T-04"
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 2,
                            Status = "dirty",
                            TableNumber = "T-05"
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 8,
                            Status = "reserved",
                            TableNumber = "T-06"
                        },
                        new
                        {
                            Id = 7,
                            Capacity = 4,
                            Status = "occupied",
                            TableNumber = "T-07"
                        },
                        new
                        {
                            Id = 8,
                            Capacity = 4,
                            Status = "idle",
                            TableNumber = "T-08"
                        },
                        new
                        {
                            Id = 9,
                            Capacity = 2,
                            Status = "idle",
                            TableNumber = "T-09"
                        },
                        new
                        {
                            Id = 10,
                            Capacity = 6,
                            Status = "idle",
                            TableNumber = "T-10"
                        },
                        new
                        {
                            Id = 11,
                            Capacity = 4,
                            Status = "idle",
                            TableNumber = "T-11"
                        },
                        new
                        {
                            Id = 12,
                            Capacity = 2,
                            Status = "occupied",
                            TableNumber = "T-12"
                        },
                        new
                        {
                            Id = 13,
                            Capacity = 6,
                            Status = "idle",
                            TableNumber = "T-13"
                        },
                        new
                        {
                            Id = 14,
                            Capacity = 4,
                            Status = "idle",
                            TableNumber = "T-14"
                        },
                        new
                        {
                            Id = 15,
                            Capacity = 8,
                            Status = "idle",
                            TableNumber = "T-15"
                        });
                });

            modelBuilder.Entity("RMS.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@rms.com",
                            FullName = "System Admin",
                            PasswordHash = "$2a$11$WJan.OEkaKtqj9Gd/C2hI.egmJavGTq/SD5IlqFp3Wa4z3ym1cj7a",
                            Role = "admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "manager@rms.com",
                            FullName = "Sarah Connor (Manager)",
                            PasswordHash = "$2a$11$BJvrMwAZgYbQbc5NIYUaOuX4B.uRjNH1yD852ddwkjEqzBa8t8AOe",
                            Role = "manager",
                            Username = "manager"
                        },
                        new
                        {
                            Id = 3,
                            Email = "chef@rms.com",
                            FullName = "Chef Gordon (Kitchen Head)",
                            PasswordHash = "$2a$11$/mNbghiXJFzIYSCPxaloSOAhX.txGljlRRm8nj8gCd/EXH5zR.5I.",
                            Role = "chef",
                            Username = "chef"
                        },
                        new
                        {
                            Id = 4,
                            Email = "waiter@rms.com",
                            FullName = "John Doe (Waiter)",
                            PasswordHash = "$2a$11$KjYrO.fwHaXh6MVLllAkDej6VbkuvVpmuv0Ry19ivJP8xLm0igjDa",
                            Role = "waiter",
                            Username = "waiter"
                        },
                        new
                        {
                            Id = 5,
                            Email = "cashier@rms.com",
                            FullName = "Jane Smith (Cashier)",
                            PasswordHash = "$2a$11$L64WC0j5E14q/re28Ky/b.InJjCX7a6JsqluqZMO/SwbWLty3sn2K",
                            Role = "cashier",
                            Username = "cashier"
                        });
                });

            modelBuilder.Entity("RMS.Api.Models.Order", b =>
                {
                    b.HasOne("RMS.Api.Models.Table", "Table")
                        .WithMany()
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RMS.Api.Models.User", "Waiter")
                        .WithMany()
                        .HasForeignKey("WaiterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Table");

                    b.Navigation("Waiter");
                });

            modelBuilder.Entity("RMS.Api.Models.OrderItem", b =>
                {
                    b.HasOne("RMS.Api.Models.MenuItem", "MenuItem")
                        .WithMany()
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RMS.Api.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("RMS.Api.Models.Payment", b =>
                {
                    b.HasOne("RMS.Api.Models.User", "Cashier")
                        .WithMany()
                        .HasForeignKey("CashierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RMS.Api.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cashier");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("RMS.Api.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
